pipeline:
  stock_symbol: "AAPL"
  split_ratio: 0.7
  sequence_length: 50
  lstm_model:
    layers:
      - LSTM:
          units: 100
          activation: 'relu'
          return_sequences: True
          input_shape: [50, 1]
      - Dropout:
          rate: 0.2
      - LSTM:
          units: 100
          activation: 'relu'
          return_sequences: True
      - Dropout:
          rate: 0.2
      - LSTM:
          units: 100
          activation: 'relu'
          return_sequences: True
      - Dropout:
          rate: 0.2
      - LSTM:
          units: 100
          activation: 'relu'
          return_sequences: True
      - Dropout:
          rate: 0.2
      - LSTM:
          units: 100
          activation: 'relu'
          return_sequences: False
      - Dropout:
          rate: 0.2
      - Dense:
          units: 1


train:
  epochs: 100
  batch_size: 32
  validation_split: 0.2
  early_stopping:
    monitor: 'val_loss'
    patience: 15
    restore_best_weights: True
  reduce_lr:
    monitor: 'val_loss'
    factor: 0.5
    patience: 5
    min_lr: 0.001
  model_checkpoint:
    filepath: "../models/lstm.model.keras"
    monitor: "val_loss"
    save_best_only: True
    mode: "min"
    verbose: 1



drift_detection:
  warning_level: 1.0
  drift_level: 2.0
  min_num_instances: 25
  feature_drift:
    threshold: 0.05
  target_drift:
    threshold: 0.05