pipeline:
  stock_symbol: "AAPL"
  split_ratio: 0.7
  sequence_length: 50
  lstm_model:
    layers:
      - LSTM:
          units: 50
          activation: 'relu'
          return_sequences: True
          input_shape: [50, 1]
      - Dropout:
          rate: 0.2
      - LSTM:
          units: 60
          activation: 'relu'
          return_sequences: True
      - Dropout:
          rate: 0.3
      - LSTM:
          units: 80
          activation: 'relu'
          return_sequences: True
      - Dropout:
          rate: 0.4
      - LSTM:
          units: 120
          activation: 'relu'
          return_sequences: False
      - Dropout:
          rate: 0.5
      - Dense:
          units: 1

train:
  epochs: 1
  batch_size: 64
  validation_split: 0.2
  early_stopping:
    monitor: 'val_loss'
    patience: 5
    restore_best_weights: True
  reduce_lr:
    monitor: 'val_loss'
    factor: 0.5
    patience: 5
    min_lr: 0.001

drift_detection:
  warning_level: 1.0
  drift_level: 2.0
  min_num_instances: 25
  feature_drift:
    threshold: 0.05
  target_drift:
    threshold: 0.05